-- 1. Tabel ROLE
CREATE TABLE ROLE (
    id_role INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nama_role VARCHAR(50) NOT NULL CONSTRAINT uq_nama_role UNIQUE
);

-- 2. Tabel USER
CREATE TABLE USERS (
    id_user INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    role_id INT NOT NULL CONSTRAINT fk_user_role REFERENCES ROLE(id_role) ON DELETE RESTRICT,
    nama_user VARCHAR(50) NOT NULL CONSTRAINT uq_nama_user UNIQUE,
    email VARCHAR(100) NOT NULL CONSTRAINT uq_email UNIQUE,
    kata_sandi VARCHAR(255) NOT NULL
);

-- 3. Tabel LOGIN
CREATE TABLE LOGINS (
    id_login INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL CONSTRAINT fk_login_user REFERENCES USERS(id_user) ON DELETE CASCADE
);

